export const FETCH_CATEGORIES_START = 'FETCH_CATEGORIES_START';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAIL = 'FETCH_CATEGORIES_FAILED';

export const SELECTED_CATEGORY_START = 'SELECTED_CATEGORY_START';
export const SELECTED_CATEGORY_SUCCESS = 'SELECTED_CATEGORY_SUCCESS';
export const SELECTED_CATEGORY_FAIL = 'SELECTED_CATEGORY_FAILED';